### ISSUE TITLE
[Bug] RPC call error

### ISSUE THREAD

**Issue by minghuaw** [minghuaw/toy-rpc#14]
> Would you be able to provide a minimal example of your use case?

That's difficult. Also maybe we should move this to a new issue since its not really related to PubSub?

_Originally posted by @jadedragon-mrm in https://github.com/minghuaw/toy-rpc/issues/6#issuecomment-882093652_ and https://github.com/minghuaw/toy-rpc/issues/6#issuecomment-882083829

**Comment by jadedragon-mrm** [comment]
To describe the use case a bit more: I'm connecting with 8 clients to 8 different RPC servers and splitting a vector into pieces which are send to the servers. The servers then respond with a bigger response and on the client side I assemble the results back to one vector.

**Comment by minghuaw** [comment]
Are the 8 clients created separated and running on separate processes?

**Comment by jadedragon-mrm** [comment]
They run in the same process

**Comment by minghuaw** [comment]
Do you have publisher on the client side publishing messages in the meantime? I think there is a race condition associated with the message id where the id stored in the `Call` struct could be different from the one assigned to the message sent to server when there is a publisher on the client side sending messages at the same time.

**Comment by jadedragon-mrm** [comment]
Also I'm using a trait like this:
```rust
#[async_trait]
#[export_trait(impl_for_client)]
pub trait StorageService {
    #[export_method]
    async fn foo(self: Arc<Self>, req: Request) -> Result<Response, toy_rpc::Error>;
}
```

I defined self as `Arc<Self>`. Maybe that has to do something with it?

**Comment by minghuaw** [comment]
> Also I'm using a trait like this:
> 
> ```rust
> #[async_trait]
> #[export_trait(impl_for_client)]
> pub trait StorageService {
>     #[export_method]
>     async fn foo(self: Arc<Self>, req: Request) -> Result<Response, toy_rpc::Error>;
> }
> ```
> 
> I defined self as `Arc<Self>`. Maybe that has to do something with it?

I think this should be fine,  but this is a little redundant because `ServerBuilder` asks for an `Arc` when you register your service, and when an RPC call is received on the server side, it internally creates a clone. But still this shouldn't affect that. I am making some changes to how the message ID is assigned and will publish a 0.8.0-alpha.1 before I start building some kind of test case.

**Comment by jadedragon-mrm** [comment]
> Do you have publisher on the client side publishing messages in the meantime? I think there is a race condition associated with the message id where the id stored in the `Call` struct could be different from the one assigned to the message sent to server when there is a publisher on the client side sending messages at the same time.

These are some lines from my log:
```DEBUG toy_rpc::client::writer:Request { id: 0, service_method: "StorageService.get_latest", timeout: 90s }    
DEBUG toy_rpc::client::writer:Request { id: 0, service_method: "StorageService.get_latest", timeout: 90s }    
DEBUG toy_rpc::client::reader:Response { id: 0, is_ok: true }    
DEBUG toy_rpc::client::reader:Response { id: 0, is_ok: true }    
ERROR toy_rpc::client::broker:Error sending over response sender line 160    
DEBUG toy_rpc::client::writer:Request { id: 1, service_method: "StorageService.get_latest", timeout: 90s }    
DEBUG toy_rpc::client::writer:Request { id: 0, service_method: "StorageService.get_latest", timeout: 90s }    
DEBUG toy_rpc::client::reader:Response { id: 1, is_ok: true } 
```

But they come from different clients running in different threads.

**Comment by jadedragon-mrm** [comment]
Also I'm using `futures_util::future::select_all` for some RPC requests. This could be a reason, because futures might be dropped.

**Comment by minghuaw** [comment]
I see. I have published 0.8.0-alpha.1 which is only a fix to the racing condition between request and publisher. I will start to build a test case for this.

**Comment by jadedragon-mrm** [comment]
I tested it and it seems to be caused by `futures_util::future::select_all`.
It should be reproducible by making several RPC calls and only awaiting the first one with `select_all`.
The other futures are discarded and as a result the error in toy_rpc occurs.
It does not happen if I call `leak` on the unused futures.

**Comment by minghuaw** [comment]
That sounds reasonable. The `futures` `oneshot::Sender` will return an error if the receiver is dropped. Do you have any recommended error message? Or I guess one option is to cancel the call when the call is dropped?

**Comment by jadedragon-mrm** [comment]
I think to cancel the call would be good, otherwise the log is full of error messages from toy_rpc which I can't suppress.

**Comment by minghuaw** [comment]
> I think to cancel the call would be good, otherwise the log is full of error messages from toy_rpc which I can't suppress.

Sounds good, I will implement that

**Comment by jadedragon-mrm** [comment]
> Sounds good, I will implement that

thanks

**Comment by jadedragon-mrm** [comment]
Do you accept donations for your work?

**Comment by minghuaw** [comment]
> Do you accept donations for your work? I would like to support your work a little.

I am doing this for fun as this moment, and I really enjoy working on this. So donation is really not needed, but still thank you for asking. It's really appreciated.

I have published 0.8.0-alpha.2 in which the call is canceled if it is dropped before results comes back from server. The task that handles incoming responses will also simply return if the call is canceled. I have only done a quick testing with a slight modification in the [tokio_tcp example](https://github.com/minghuaw/toy-rpc/blob/6dfd95acf8204beb9618968ac76c7c8be0e31b1f/examples/tokio_tcp/src/bin/client.rs#L35). 

Feel free to let me know if there is any bugs or features you want.

**Comment by minghuaw** [comment]
I forgot to mention that as a result of the change, `cancel()` method on the `Call` now requires a mutable reference.

**Comment by jadedragon-mrm** [comment]
> I am doing this for fun as this moment, and I really enjoy working on this. So donation is really not needed, but still thank you for asking. It's really appreciated.

Ok. In case you change your mind let me know :)

> I have published 0.8.0-alpha.2 in which the call is canceled if it is dropped before results comes back from server. The task that handles incoming responses will also simply return if the call is canceled. I have only done a quick testing with a slight modification in the [tokio_tcp example](https://github.com/minghuaw/toy-rpc/blob/6dfd95acf8204beb9618968ac76c7c8be0e31b1f/examples/tokio_tcp/src/bin/client.rs#L35).
> 
> Feel free to let me know if there is any bugs or features you want.

I upgraded my project to the newest version. So far I'm very happy with it. I don't see any errors.
The only thing left would be the issue with `anyhow`.

**Comment by minghuaw** [comment]
> The only thing left would be the issue with `anyhow`.

I am still trying to find an elegant solution for this. My understanding is that the ideal case for you would be that you can use `anyhow::Result` in the RPC trait declaration. Is that right?

**Comment by jadedragon-mrm** [comment]
> I am still trying to find an elegant solution for this. My understanding is that the ideal case for you would be that you can use `anyhow::Result` in the RPC trait declaration. Is that right?

Yes, but for now I would be happy if I can use `?` on `anyhow::Result`. I added an example in the other issue.
