### ISSUE TITLE
Is the project still in active development?

### ISSUE THREAD

**Issue by ngryman** [minghuaw/toy-rpc#24]
Hey @minghuaw,

First of all thanks for this library, it's very well thought and designed 👏 

I guess everything is in the title of this issue 😄 
I'm asking because I'm starting a SaaS and I'm already using your library with success. But before I fully commit to using it I'd like to be confident enough that it will not be abandoned.

Thanks!

**Comment by minghuaw** [comment]
After reading the `tarpc`'s [release notes](https://github.com/google/tarpc/blob/2591d21e94803c9fda53decc2c2b81fdd17aa65d/RELEASES.md), 

> client cancellation propagation: when a client drops a request, the client sends a message to the server informing it to cancel its response. This means cancellations can propagate across multiple server hops.

I just realized that cascading cancellation is already supported. Whenever a `Call<Res>` is dropped, a cancellation will be sent to the server if the response has not been received by the `Call`, which is essentially the same mechanism as that in `tarpc`

**Comment by ngryman** [comment]
Oh, that's great!
