### ISSUE TITLE
error[E0433]: failed to resolve: use of undeclared type `ConsumerHandlerRegistry`

### ISSUE THREAD

**Issue by DevasiaThomas** [minghuaw/toy-rpc#36]
Hi @minghuaw I exported the declaration of the rpc to a crate that i publish and then i use it as a dependency and define it on server side. I don't really understand how to solve this problem(the above error).

**Definition Lib**
``cargo.toml``
```
[package]
name = "rpc-lib"
version = "0.0.1"
authors = ["xyz",]
edition = "2021"

[lib]
bench = false

[dependencies]
anyhow = "1"
toy-rpc = { version = "0.8.4", features = [] }
async-trait = "0.1"
```

``src/lib.rs``
```
pub use async_trait::async_trait;
use toy_rpc::macros::export_trait;
use anyhow::{Result};


#[async_trait]
#[export_trait(impl_for_client)]
pub trait Consumer {
    #[export_method]
    async fn consume(&self, message: Vec<u8>) -> Result<()>;
}
```
The above gets published and then used below in the server

**Server**
I use the dependency in ``cargo.toml``
```
[package]
name = "rpc-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
flume = "0.10"
rpc-lib = {version = "0.0.1"}
tokio = { version = "1", features = ["full"] }
toy-rpc = { version = "0.8.4", features = ["tokio_runtime", "server", "anyhow"] }
```

``rpc_impl.rs``
```
use anyhow::Result;
use flume::Sender;
use rpc_lib::async_trait;

use toy_rpc::macros::export_trait_impl;

pub struct Consumer {
    pub tx: Sender<Vec<u8>>,
}

#[async_trait]
#[export_trait_impl]
impl rpc_lib::Consumer for Consumer {//-------> Error happens here
    async fn consume(&self, message: Vec<u8>) -> Result<()> {
        //Send data on sender
        Ok(())
    }
}

```
The main is a simple tcp server and is exactly similar to your examples that use tcp. Starts a listener, instantiates the consumer, instantiates the server and registers the consumer and then accepts over the listener.

Any insight is appreciated.

**Comment by DevasiaThomas** [comment]
Well apparently  a ``use rpc_lib::*;`` fixes the issue, i'm assuming there is some generated code magic going on here....

**Comment by minghuaw** [comment]
> Well apparently a `use rpc_lib::*;` fixes the issue, i'm assuming there is some generated code magic going on here....

I was just going to say that. The generated code for server doesn't know where the service is defined. I guess I could probably add a argument to the macro where the user could specify the path to the service crate/mod

**Comment by DevasiaThomas** [comment]
@minghuaw maybe you could have it called a stub that calls No-OP code pre-generation and the correct handler after code generation? 
The only reason I ask this is because I could have a lot of other things in that lib.rs and this would import all of that. If you say the best practice for your library is to keep the rpc definition in its own file that works too.

About the path to crate/mod, idk how this works exactly, but you know best :) I'll leave it up to you. Anything that makes your library better :)

Happy holidays :D !

**Comment by minghuaw** [comment]
Keeping the service in its own file/mod is probably the best practice for now. Let me think about a better way
