### ISSUE TITLE
frame large payloads write issue

### ISSUE THREAD

**Issue by jadedragon-mrm** [minghuaw/toy-rpc#4]
Hi,
it seems there is an issue in transport/frame.rs when using the tokio runtime.

https://github.com/minghuaw/toy-rpc/blob/ab4cc9b0859743ef5d1a8909cce38fa299bb7704/toy-rpc/src/transport/frame.rs#L227-L233

 
The write fails for large payloads and maybe should be replaced with `write_all`.

**Comment by minghuaw** [comment]
Can you provide a bit more information? How large was the payload?

**Comment by minghuaw** [comment]
@jadedragon-mrm I have replaced the `write` with `write_all` and rolled up the version to 0.7.1. Could you please check if that helps?

Please note that the frame transport currently only implements one body frame, and this limits the maximum payload size to `u32::Max` (bytes).

**Comment by jadedragon-mrm** [comment]
Yes thanks. That helps

**Comment by minghuaw** [comment]
> Yes thanks. That helps

On that note, I will close this issue for now.
