### ISSUE TITLE
Request: Support Stubborn IO

### ISSUE THREAD

**Issue by jadedragon-mrm** [minghuaw/toy-rpc#5]
Currently toy-rpc clients seem not to work with a StubbornTcpStream (https://docs.rs/stubborn-io/0.3.1/stubborn_io/tokio/type.StubbornTcpStream.html) instead of the default tokio TcpStream, because  the implementation requieres a stream to be Sync:

https://github.com/minghuaw/toy-rpc/blob/aa580f102f015de18ace91bacd7d5767c94cf52b/toy-rpc/src/client/tokio.rs#L198-L204

If the requirement for streams to be Sync is removed, it can be used with the StubbornTcpStream.

**Comment by minghuaw** [comment]
@jadedragon-mrm Thank you for picking up the problem with the trait bounds. I have been wanting to relax the trait requirements but keep forgetting about it.

I have removed `Sync` from the trait bounds in version 0.7.2. Please take a look and feel free to let me know if there is anything else I can help.

**Comment by jadedragon-mrm** [comment]
Great. That solves the problem
