### ISSUE TITLE
[Feature Request] PubSub

### ISSUE THREAD

**Issue by jadedragon-mrm** [minghuaw/toy-rpc#6]
Currently a RPC client can be created from a TCPStream and a RPC server from a TcpListener using the `accept` method.
In order to be able to make calls in the reverse direction it would be great to support creating a RPC client from a TcpListener as well.
This way the RPC client can be a TCP server and the RPC server a TCP client. With this feature it would be possible to implement bidirectional communication with one TCP connection for the forward direction and another TCP connection for the reverse direction (probably running on different ports though).

**Comment by minghuaw** [comment]
This feature sounds interesting and would likely need some re-structuring of the existing code. As I am not planning to re-structure the code in the near future, it may take a long time before this is implemented. Could you please provide some usage proposal? @jadedragon-mrm 

Meanwhile, I think what you can implement for now is to start two RPC servers, one on each end, to achieve something similar to bidirectional RPC.

**Comment by jadedragon-mrm** [comment]
I want to implement a TCP Server which periodically sends updates to the TCP client. If the TCP client is behind a firewall and not publicly accessible it is not possible to create another RPC server locally for the reverse direction.

**Comment by jadedragon-mrm** [comment]
Something similar has been implemented in this example with the tarpc library:
https://github.com/google/tarpc/blob/master/tarpc/examples/pubsub.rs

**Comment by minghuaw** [comment]
I was planning to implement something similar to a PubSub or message queue in a separate crate. I am now considering adding this feature in the major release (it's probably going to take me a few days thinking through how to make it easy to use). 

Meanwhile, feel free to let me know something like an example usage case or API for you.

**Comment by minghuaw** [comment]
@jadedragon-mrm One temporary solution for you could be that you can have the service maintaining a state with a buffer of pubsub items. There will be a RPC method that publishes to the service and there will be another RPC method that retrieves one item from the buffer (polling basically).

**Comment by jadedragon-mrm** [comment]
Yes, but I don't want to add unnecessary delays with the polling. I think two separate TCP connections for both directions is what I need, so there is no blocking or waiting for the other channel.

**Comment by minghuaw** [comment]
@jadedragon-mrm I am exploring the design of the APIs and would like to discuss with you whether that sounds reasonable. So overall, the publisher/subscriber can be built with client, and there will be three methods.

 1. Add topic 
    ```rust
    // where
    //     Topic: ToString,
    //     MessageType: Serializer + Deserialize
    client.add_topic::<Topic<MessageType>>();
    ```
 2. A publisher is bound with only one Topic and one message type
    ```rust
    let publisher: impl Sink<MessageType> = client.publisher::<Topic<MessageType>>();
    ```
 3. A subscriber is also bound with only one Topic and one message type
    ```rust
    let subscriber: impl Stream<Item=MessageType> = client.subscriber::<Topic<MessageType>>();
    ```

What do you think about this design?

**Comment by jadedragon-mrm** [comment]
I'm not sure an add_topic method would be needed. Who would call this? I think this could be done implicitly by creating the subscriber or publisher. Also I would request that `publisher::<Topic>();` can be called on the server as well, not just on clients.

**Comment by minghuaw** [comment]
> I'm not sure an add_topic method would be needed. Who would call this? I think this could be done implicitly by creating the subscriber or publisher. 

I am debating whether `add_topic` is necessary. Everything can be done implicitly indeed. 

> Also I would request that `publisher::<Topic>();` can be called on the server as well, not just on clients.

I disagree on this. One can simply spin up a client on the server machine and periodically publish to the topic, and thus I don't really see the necessity of adding this functionality on the server. Plus, the server will likely be a message relay for the pubsub and may be not aware of the type of the message.

**Comment by minghuaw** [comment]
> > Also I would request that `publisher::<Topic>();` can be called on the server as well, not just on clients.
> 
> I disagree on this. One can simply spin up a client on the server machine and periodically publish to the topic, and thus I don't really see the necessity of adding this functionality on the server. Plus, the server will likely be a message relay for the pubsub and may be not aware of the type of the message.

Actually I guess this should be the decision of the user. So I think what I will do is that the server side will also be able to call `publisher::<Topic>()` and `subscriber::<Topic>()`.

**Comment by minghuaw** [comment]
Just to summarize, what will likely be implemented are:

1. On the client side:
```rust
let publisher: impl Sink<MessageType> = client.publisher::<Topic>();
let subscriber: impl Stream<Item=MessageType> = client.subscriber::<Topic>();
```

2. On the server side:
```rust
let publisher: impl Sink<MessageType> = server.publisher::<Topic>();
let subscriber: impl Stream<Item=MessageType> = server.subscriber::<Topic>();
```

Feel free to let me know if there is any other feature you would like to see.

**Comment by minghuaw** [comment]
PubSub will require sending request/response bidirectionally, which is not implemented in the message protocol in 0.7. Due to breaking change in the message protocol, this feature will only be implemented in the next major release (0.8). As of now, there is no fixed timeline of when the next release will come out.

**Comment by jadedragon-mrm** [comment]
> Just to summarize, what will likely be implemented are:
> 
> 1. On the client side:
> 
> ```rust
> let publisher: impl Sink<MessageType> = client.publisher::<Topic>();
> ```
> 
> ```rust
> let subscriber: impl Stream<Item=Result<MessageType, Error>> = client.subscriber::<Topic>();
> ```
> 
> 1. On the server side:
> 
> ```rust
> let publisher: impl Sink<MessageType> = server.publisher::<Topic>();
> ```
> 
> ```rust
> let subscriber: impl Stream<Item=Result<MessageType, Error>> = server.subscriber::<Topic>();
> ```
> 


Great! This is exactly what I would like to use.
Can you give a rough estimate for when you'll be working on the 0.8 release?

**Comment by minghuaw** [comment]
> Can you give a rough estimate for when you'll be working on the 0.8 release?

I am designing the new protocol and have encountered a bug with `erased_serde` which I have already made a PR. If the PR is merged by the end of this week, my rough estimate for 0.8 would be somewhere around this Sunday.

**Comment by jadedragon-mrm** [comment]
Ok. I'm looking forward to test this new feature. If you need my help with anything, let me know.

**Comment by minghuaw** [comment]
> Ok. I'm looking forward to test this new feature. If you need my help with anything, let me know.

I have run into some personal issues. Please expect some delays (two or three days) for the 0.8.0-alpha

**Comment by jadedragon-mrm** [comment]
Ok no problem

**Comment by jadedragon-mrm** [comment]
Is the PubSub feature now working in the 0.8-alpha branch?

**Comment by minghuaw** [comment]
> Is the PubSub feature now working in the 0.8-alpha branch?

Sorry, not yet. I am still working on it. It's been really hard to stay productive because of recent heat wave in my city

**Comment by minghuaw** [comment]
@jadedragon-mrm Would you want something that allows multiple subscribers of the same topic on one client?

**Comment by jadedragon-mrm** [comment]
I think one subscriber of the same topic per client should be enough.
One thing that could be useful though is to define a maximum queue size for the subscriber, in case the subscriber cannot process the messages fast enough.

**Comment by minghuaw** [comment]
There is now an initial implementation with tag [`0.8.0-pre-alpha.1`](https://github.com/minghuaw/toy-rpc/releases/tag/0.8.0-pre-alpha.1) and a working example in the 0.8-alpha branch [here](https://github.com/minghuaw/toy-rpc/tree/0.8-alpha/examples/tokio_pubsub). 

I still need to do more testing, cleanup and  troubleshoot some bugs before finalizing this version.

**Comment by jadedragon-mrm** [comment]
Ok, does calling `publisher` and `subscriber` also work for the server in this alpha version?

> ```rust
> let publisher = server.publisher::<Topic>();
> ```

> ```rust
> let subscriber = server.subscriber::<Topic>();
> ```

**Comment by minghuaw** [comment]
> Ok, does calling `publisher` and `subscriber` also work for the server in this alpha version?

`publisher::<Topic>()` and `subscriber::<Topic>()` implementations are just added on the server side in tag [`0.8.0-pre-alpha.2`](https://github.com/minghuaw/toy-rpc/releases/tag/0.8.0-pre-alpha.2) and should work in the 0.8-alpha branch. The [tokio_pubsub example](https://github.com/minghuaw/toy-rpc/tree/0.8-alpha/examples/tokio_pubsub) is also updated to demonstrate the usage.

**Comment by minghuaw** [comment]
@jadedragon-mrm I am debating whether a PubSub message should be followed with an `Ack`. Any idea?

**Comment by jadedragon-mrm** [comment]
The TCP protocol itself already sends `ACK` packets. I my opinion that's enough.
But if someone really needs an explicit `ACK` then they could define it manually:
```rust
//on the client side
client.publisher::<Count>();
client.subscriber::<Ack>(10).unwrap();

//on the server side
server.subscriber::<Count>(10).unwrap();
server.publisher::<Ack>();
 ```

This way the `Ack` can also contain useful serialized data.

**Comment by minghuaw** [comment]
I have published 0.8.0-alpha.0 on crates.io. The documentation be updated for PubSub.

**Comment by jadedragon-mrm** [comment]
Great! I will try it

**Comment by jadedragon-mrm** [comment]
I'm getting regularly the message `toy_rpc::client::broker:Error sending over response sender`.
I think the error is not very descriptive. It might have something to do with the subscriber reaching it's maximum capacity.

**Comment by minghuaw** [comment]
> I'm getting regularly the message `toy_rpc::client::broker:Error sending over response sender`.
> 
> Possibly though the error has nothing to do with the PubSub and happens on RPC calls.

That error message is associated with RPC calls. Can you provide more information like what kind of RPC calls you were making?
The error message itself is worded really bad, so I will try to improve the error message as well.

**Comment by jadedragon-mrm** [comment]
It seems to happen in `clien/broker.rs` on line 160.
Yes it happens with RPC calls. I have several threads running which make requests simultaneously. So this might be a mulithreading issue.

**Comment by minghuaw** [comment]
> It seems to happen in `client/broker.rs` on line 160.
> Yes it happens with RPC calls. I have several threads running which make requests simultaneously. So this might be a mulithreading issue.

Would you be able to provide a minimal example of your use case?

**Comment by jadedragon-mrm** [comment]
> Would you be able to provide a minimal example of your use case?

That's difficult. Also maybe we should move this to a new issue since its not really related to PubSub?

**Comment by minghuaw** [comment]
Moving the RPC call related bugs to #14

**Comment by minghuaw** [comment]
A new derive macro `Topic` is added in version 0.8.0-alpha.4 to generate impl for the `Topic` trait. Example usage

```rust
use toy_rpc::macros::Topic; // The trait`Topic` is still defined in `toy_rpc::pubsub::Topic`
use serde::{Serialize, Deserialize};

#[derive(Topic, Serialize, Deserialize)] // Here `Count` type will be the associated type `Topic::Item`
pub struct Count(u32);
```

**Comment by fog-gmbh** [comment]
> A new derive macro `Topic` is added in version 0.8.0-alpha.4 to generate impl for the `Topic` trait.

That's great. Will the name of the topic be transmitted on every request?

So if I do this:

> ```rust
> #[derive(Topic, Serialize, Deserialize)]
> pub struct MyTopicWithAVeryVeryVeryVeryVeryVeryLongName(u32);
> ```

Will this cost more bandwidth than choosing a short name for the topic?

If so, maybe the derive macro could generate a shorter ID for the topic. For example a 32bit hash instead of the full name.

**Comment by minghuaw** [comment]
> Will this cost more bandwidth than choosing a short name for the topic?

Good point. I never thought about this. The topic name is indeed transmitted on every request. I guess the workaround for now is to manually implement the `Topic` trait to reduce the cost on bandwidth. 

> If so, maybe the derive macro could generate a shorter ID for the topic. For example a 32bit hash instead of the full name.

This could be a good option. My only concern is that a 32bit hash would look bad on the log. Let me think about it.

**Comment by fog-gmbh** [comment]
> This could be a good option. My only concern is that a 32bit hash would look bad on the log. Let me think about it.

Or maybe there could be two macros `Topic` and `TopicHash` and then the user can choose what is more important: nice logs or lower bandwidth cost.

**Comment by minghuaw** [comment]
> > This could be a good option. My only concern is that a 32bit hash would look bad on the log. Let me think about it.
> 
> Or maybe there could be two macros `Topic` and `TopicHash` and then the user can choose what is more important: nice logs or lower bandwidth cost.
> 
> Or check whether it is running in a debug or release build. In the debug build the full name can be transmitted, but in the release build only the hash will be used.

Good ideas. I will probably go with something that can be configured with additional attribute args.

**Comment by minghuaw** [comment]
There is a minor change in API in 0.8.0-beta.0. When you create a `Subscriber`, the method now takes an `Option<NonZeroUsize>` as the argument (ie. `subscriber::<Topic>(Option<NonZeroUsize>)` ). When the argument is `None`, the subscriber will be created with an unbounded channel under the hood. The usage would then look like

```rust
// This will create a subscriber with a buffer size of 10
let subscriber = client.subscriber::<Count>(NonZeroUsize::new(10)).unwrap();
```

**Comment by fog-gmbh** [comment]
> ```rust
> #[derive(Serialize, Deserialize, Topic)
> #[topic(rename="C")] // This will only change topic name to "C", and the message item type is still `Count`
> pub struct Count(u32);
> ```

I think that's very useful.


> ```rust
> #[derive(Topic)
> #[topic(item = "u32")] // This will only change the message item type
> pub struct Count { }
> ```

So the use case of this is to directly work with u32 numbers without having to wrap them in a struct?

**Comment by jadedragon-mrm** [comment]
> ```rust
> #[derive(Serialize, Deserialize, Topic)
> #[topic(rename="C")] // This will only change topic name to "C", and the message item type is still `Count`
> pub struct Count(u32);
> ```

I think that's very useful.


> ```rust
> #[derive(Topic)
> #[topic(item = "u32")] // This will only change the message item type
> pub struct Count { }
> ```

So the use case of this is to directly work with u32 numbers without having to wrap them in a struct?

**Comment by minghuaw** [comment]
> So the use case of this is to directly work with u32 numbers without having to wrap them in a struct?

That is correct. The item type must implement `Serialize` and `Deserialize`. And the struct `Count` will only be used for declaring 
the topic, which kind of allows some check at the compile time.

**Comment by minghuaw** [comment]
@jadedragon-mrm @fog-gmbh I am debating whether a new feature flag "pubsub" should be added to hide PubSub behind a feature gate? Any ideas?

**Comment by fog-gmbh** [comment]
> @jadedragon-mrm @fog-gmbh I am debating whether a new feature flag "pubsub" should be added to hide PubSub behind a feature gate? Any ideas?

I think hiding something behind a feature flag makes only sense if you also can make some otherwise not needed dependencies optional.
For example what I would like is a feature flag "websockets". With this feature flag `tungstenite` could become optional and all of its dependencies don't have to be included in my project, because I only use TCP communication.

**Comment by jadedragon-mrm** [comment]
> @jadedragon-mrm @fog-gmbh I am debating whether a new feature flag "pubsub" should be added to hide PubSub behind a feature gate? Any ideas?

I think hiding something behind a feature flag only makes sense if you also can make some otherwise not needed dependencies optional.
For example what I would like is a feature flag "websockets". With this feature flag `tungstenite` could become optional and all of its dependencies don't have to be included in my project, because I only use TCP communication.

(Before I accidentally used the wrong github account to reply.)

**Comment by minghuaw** [comment]
@jadedragon-mrm The WebSocket related crates and APIs (including `dial_http` and `dial_websocket`) are not feature gated behind a new feature flag "ws" in version `"0.8.0-beta.4"`. The `tokio_tcp` example will compile with 151 dependencies without `"ws"` feature and 165 dependencies with `"ws"` feature.

**Comment by jadedragon-mrm** [comment]
https://github.com/minghuaw/toy-rpc/blob/a230926ea9e678e0b64d33ce2484632c0088a18b/toy-rpc/Cargo.toml#L46-L47

It seems `async-tungstenite` still gets pulled in by the features `tokio_runtime` and `async_std_runtime`.

**Comment by minghuaw** [comment]
> It seems `async-tungstenite` still gets pulled in by the features `tokio_runtime` and `async_std_runtime`.

Good catch. The `"ws"` feature is now split into two separate feature flags: `"ws_tokio"` and `"ws_async_std"` to work with different async runtime in version `"0.8.0-beta.5"`. The `tokio_tcp` example now compiles with 124 dependencies.

**Comment by jadedragon-mrm** [comment]
Great! I tested it and it works.

**Comment by minghuaw** [comment]
The change from 0.8.0-beta.5 to 0.8.0 is only a bug fix for websocket closing handshake, and I am not adding any feature flags to toggle the pubsub functionality.  So I think the 0.8.0 version should not introduce any breaking changes for you. I will close this issue for now.
