### ISSUE TITLE
Add default timeout duration?

### ISSUE THREAD

**Issue by minghuaw** [minghuaw/toy-rpc#9]
This is the tracking issue for discussion on a default timeout duration in version 0.8

**Comment by minghuaw** [comment]
Two options are being considered. 

1. Having a global default timeout duration (say something like 10 seconds)
2. The client can configure a default timeout.

**Comment by jadedragon-mrm** [comment]
I would prefer the second option:
`client.set_default_timeout(duration: Duration)`

**Comment by minghuaw** [comment]
Now a default timeout of 10 seconds is set when a new client is created, but the default timeout can be changed with `set_default_timeout(duration)`. If you are interested in setting the timeout only for the next RPC call, there is another method `set_next_timeout(duration)`

**Comment by minghuaw** [comment]
Re-opening this issue for future discussions on changing timeouts
